name: Build, Run, and Upload ONNX-MD-Parser Metadata

on:
  push:
    paths:
      - 'tools/onnx-md-parser/**'
      - 'models/**'
      - '.github/workflows/onnx-md-parser.yml'

  workflow_dispatch:

jobs:
  build-run-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Clone Aimmy models folder
      run: |
        git clone --filter=blob:none --sparse https://github.com/babyhamsta/aimmy.git temp-aimmy
        cd temp-aimmy
        git sparse-checkout set models
        cp -r models/* ../models/ || true
        cd ..
        rm -rf temp-aimmy

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Build ONNX-MD-Parser
      run: |
        cd tools/onnx-md-parser
        dotnet build --configuration Release

    - name: Run ONNX-MD-Parser on ONNX models
      run: |
        cd tools/onnx-md-parser/bin/Release/net8.0
        ./onnx-md-parser --dir ../../../../../models --md-path ../../../../../models/metadata.json --ignore true

    - name: Commit and Push Metadata
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        ls
        git add models/metadata.json
        git commit -m "chore: update metadata.json from ONNX-MD-Parser workflow"
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
